spring.application.name=placementhub

# MongoDB Connection
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/placementhub}

# Security & JWT Secrets (Keep these private in production)
placementhub.jwt.secret=${JWT_SECRET:pLaCeMeN2Nt51827f8a9b2c4d6e1f3a5b8c9d2e4f6a1b3c5d7e9f2a4b6c8d0e1f3a5b7c9d2e4f6a}
placementhub.jwt.expiration=${JWT_EXPIRATION_MS:86400000}

app.frontend.url=${FRONTEND_URL:http:127.0.0.17:5173/}

# Server Port
server.port=${PORT:8080}